// apps/food/app/components/Breadcrumbs.vue
<template>
  <div class="mb-6 flex flex-row justify-between items-center">
    <nav class="hidden lg:block">
      <ol class="flex flex-row flex-wrap gap-y-2 items-center">
        <li v-for="link in links" :key="link.title" class="relative max-w-[20rem] after:content-['/'] after:px-1 after:text-lg after:text-neutral-300 last:after:content-['']">
          <NuxtLink
            :to="link.href"
            class="px-3 py-2 inline-block leading-tight rounded-xl active:scale-95 lg:hover:bg-neutral-200 lg:hover:scale-95 lg:active:scale-90 duration-200 bg-neutral-50 dark:bg-neutral-700 data-[active=true]:bg-neutral-50"
            :data-active="link.href === '#'"
          >
            {{ link.title }}
          </NuxtLink>
        </li>
      </ol>
    </nav>

    <div class="w-full lg:w-auto mx-auto md:mx-0">
      <UiButton variant="secondary" @click="back()">
        <div class="flex flex-row gap-2 justify-center items-center">
          <Icon :name="icons.undo" size="20" /> {{ $t('common.return') }}
        </div>
      </UiButton>
    </div>
  </div>
</template>

<script setup lang="ts">
const { links } = defineProps<{
  links: { title: string, href: string }[]
}>()

const { icons } = useAppConfig()
const { back } = useRouter()
</script>

// apps/storefront-v1/src/components/Breadcrumbs.tsx
import Link from 'next/link';
import { GetChannel } from '../client/api';
import { BackBlock } from './BackBlock';

export type BreadcrumbLink = {
  title: string;
  href: string;
};

type BreadcrumbsProps = {
  links: BreadcrumbLink[];
};

export const Breadcrumbs = async ({ links }: BreadcrumbsProps) => {
  const channel = await GetChannel();
  const locale = channel?.languageCode ?? 'EN';

  const breadcrumbItems = links.map((link) => (
    <BreadcrumbItem key={link.href} link={link} />
  ));

  return (
    <div className="mb-6 flex flex-row justify-between items-center">
      <nav className="hidden lg:block">
        <ol className="flex flex-row flex-wrap gap-y-2 items-center">
          {breadcrumbItems}
        </ol>
      </nav>

      <BackBlock locale={locale} />
    </div>
  );
};

type BreadcrumbItemProps = {
  link: BreadcrumbLink;
};

const BreadcrumbItem = ({ link }: BreadcrumbItemProps) => (
  <li className="relative max-w-[20rem] after:content-['/'] after:px-1 after:text-lg after:text-zinc-300 last:after:content-['']">
    <Link
      href={link.href}
      className="px-3 py-2 inline-block leading-tight rounded-xl active:scale-95 lg:hover:bg-zinc-200 lg:hover:scale-95 lg:active:scale-90 duration-200 bg-zinc-50 data-[active=true]:bg-zinc-50"
      data-active={link.href === '#'}
    >
      {link.title}
    </Link>
  </li>
);
