// apps/food/app/components/Cart/index.vue
<template>
  <div v-if="checkout" class="relative bg-white dark:bg-gray-600 rounded-2xl px-4 py-4 h-full flex flex-col justify-between">
    <div class="h-screen overflow-y-auto">
      <div class="mb-48">
        <div class="mb-4 flex flex-row justify-between items-center">
          <p class="text-2xl font-medium">
            {{ $t('app.cart.title') }}
          </p>

          <button
            aria-label="Close"
            class="block xl:hidden rounded-xl lg:hover:scale-90 hover:bg-gray-100 duration-200"
            @click="isCartDrawerOpened = !isCartDrawerOpened"
          >
            <Icon :name="icons.close" class="w-8 h-8" />
          </button>
        </div>

        <div class="mt-2 mb-4">
          <CartDeliveryMethodSwitch />
        </div>

        <CartEmpty v-if="isEmpty" />
        <div v-else>
          <CartLine v-for="line in checkout?.lines" :key="line.id" :line-id="line.id" />
        </div>
      </div>
    </div>

    <div class="absolute bottom-0 left-0 right-0 rounded-2xl bg-gray-50 dark:bg-gray-700">
      <button
        class="relative my-4 mx-4 flex flex-row gap-3 flex-wrap items-center active:scale-95 lg:hover:scale-95 lg:active:scale-90 duration-200"
        @click="isDeliveryInfoModalOpened = !isDeliveryInfoModalOpened"
      >
        <Icon :name="icons.info" class="w-8 h-8 text-gray-300" />

        <div class="text-left">
          <CartDeliveryInfo />

          <div class="text-sm text-gray-500">
            {{ $t('app.cart.conditions') }}
          </div>
        </div>
      </button>

      <div v-if="!isEmpty" class="my-4 mx-4">
        <NuxtLink
          to="/checkout"
          class="button-gradient w-full px-4 py-4 flex flex-row gap-2 flex-wrap justify-between items-center rounded-xl cursor-pointer active:scale-95 lg:hover:scale-95 lg:active:scale-90 duration-200"
        >
          <div class="font-normal">
            {{ $t('app.cart.next-label') }}
          </div>
          <div class="font-medium text-lg tracking-tight">
            {{ checkout?.totalPrice }} <span class="text-base">₽</span>
          </div>
        </NuxtLink>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
const { isCartDrawerOpened, isDeliveryInfoModalOpened } = useApp()
const { icons } = useAppConfig()
const { checkout, isEmpty } = await useCheckout()
</script>

// apps/storefront-v1/src/components/Cart.tsx
'use client';

import Image from 'next/image';
import Link from 'next/link';
import { IconInfoHexagon, IconX } from '@tabler/icons-react';
import type {
  Channel,
  Checkout,
  CheckoutLine,
  CurrencyCode,
} from '@next-orders/api-sdk';
import { Counter } from './Counter';
import { Price } from './Price';
import { CartDeliveryMethodToggle } from './CartDeliveryMethodToggle';
import { useUIStore } from '../store/ui';
import { getDictionary, Locale } from '../dictionaries';
import {
  DEFAULT_IMAGE_URL,
  getCurrencySign,
  getProductFirstPhoto,
  getWeightLocalizedUnit,
} from '../client/helpers';

type CartProps = {
  channel: Channel | null;
  checkout: Checkout | null;
};

export const Cart = ({ channel, checkout }: CartProps) => {
  const closeCartDrawer = useUIStore((state) => state.closeCartDrawer);
  const toggleDeliveryInfoModal = useUIStore(
    (state) => state.toggleDeliveryInfoModal,
  );

  const locale = channel?.languageCode ?? 'EN';
  const { CART_LABEL, CART_NEXT_BUTTON, DETAILED_CONDITIONS_LABEL } =
    getDictionary(channel?.languageCode);

  const items = checkout?.lines?.map((line) => (
    <CartItemLine
      key={line.id}
      locale={locale}
      currencyCode={channel?.currencyCode}
      {...line}
    />
  ));

  const isEmpty = items?.length === 0;

  const backgroundColor = channel?.accentButtonColor;
  const backgroundImage = `linear-gradient(to bottom right, ${channel?.accentGradientFrom}, ${channel?.accentGradientTo})`;

  const currencySign = getCurrencySign(channel?.currencyCode);

  if (!checkout) {
    return null;
  }

  return (
    <div className="relative bg-white rounded-2xl px-4 py-4 h-full flex flex-col justify-between">
      <div className="h-screen overflow-y-auto">
        <div className="mb-48">
          <div className="mb-4 flex flex-row justify-between items-center">
            <p className="text-2xl font-medium">{CART_LABEL}</p>

            <button
              onClick={closeCartDrawer}
              aria-label="Close"
              className="block xl:hidden rounded-xl lg:hover:scale-90 hover:bg-zinc-100 duration-200"
            >
              <IconX stroke={1.5} className="w-8 h-8" />
            </button>
          </div>

          <div className="mt-2 mb-4">
            <CartDeliveryMethodToggle channel={channel} checkout={checkout} />
          </div>

          {isEmpty && <CartEmpty locale={locale} />}
          {items}
        </div>
      </div>

      <div className="absolute bottom-0 left-0 right-0 rounded-2xl bg-zinc-50">
        <button
          onClick={toggleDeliveryInfoModal}
          className="relative my-4 mx-4 flex flex-row gap-3 flex-wrap items-center active:scale-95 lg:hover:scale-95 lg:active:scale-90 duration-200"
        >
          <IconInfoHexagon stroke={1.5} className="w-8 h-8 text-zinc-300" />

          <div className="text-left">
            <DeliveryInfoBlock
              method={checkout?.deliveryMethod || 'DELIVERY'}
              shippingPrice={checkout?.shippingPrice || 0}
              currencySign={currencySign}
              locale={locale}
            />

            <div className="text-sm text-zinc-500">
              {DETAILED_CONDITIONS_LABEL}
            </div>
          </div>
        </button>

        {!isEmpty && (
          <div className="my-4 mx-4">
            <Link
              href={'/checkout'}
              className="w-full px-4 py-4 flex flex-row gap-2 flex-wrap justify-between items-center rounded-xl cursor-pointer active:scale-95 lg:hover:scale-95 lg:active:scale-90 duration-200"
              style={{ backgroundColor, backgroundImage }}
            >
              <div className="font-normal">{CART_NEXT_BUTTON}</div>
              <div className="font-medium text-lg tracking-tight">
                {checkout?.totalPrice}
                <span className="pl-1 text-base">{currencySign}</span>
              </div>
            </Link>
          </div>
        )}
      </div>
    </div>
  );
};

type CartItemLineProps = {
  locale: Locale;
  currencyCode: CurrencyCode | undefined;
} & CheckoutLine;

const CartItemLine = ({
  locale,
  currencyCode,
  quantity,
  productVariant,
  id,
}: CartItemLineProps) => {
  const price = productVariant?.gross * quantity;
  const firstPhoto = getProductFirstPhoto(productVariant.media);

  const currencySign = getCurrencySign(currencyCode);

  const weightUnitLocalized = getWeightLocalizedUnit(
    productVariant.weightUnit,
    locale,
  );

  // Prepare Item URL
  const pageUrl = `/catalog/${productVariant.category.slug}/${productVariant.slug}`;

  return (
    <div className="mb-4 flex flex-row gap-2 items-center justify-between">
      <Link href={pageUrl}>
        <div className="max-w-[15rem] flex flex-row gap-2 flex-nowrap items-center cursor-pointer active:scale-95 lg:hover:scale-95 lg:active:scale-90 duration-200 group">
          <div className="relative w-14 h-14 aspect-square">
            <Image
              src={firstPhoto?.url ?? DEFAULT_IMAGE_URL}
              alt={firstPhoto?.alt ?? ''}
              fill
              sizes="(min-width: 1024px) 20vw, (min-width: 768px) 25vw, (min-width: 640px) 33vw, (min-width: 475px) 50vw, 100vw"
              className="rounded-xl object-cover object-center xl:grayscale xl:contrast-75 xl:brightness-125 group-hover:grayscale-0 group-hover:contrast-100 group-hover:brightness-100"
            />
          </div>

          <div>
            <p className="font-base text-xs leading-tight line-clamp-2">
              {productVariant.name}
            </p>
            <div className="mt-1 flex flex-row gap-2 flex-nowrap">
              <div className="text-sm font-medium tracking-tight">
                <Price value={price} />
                <span className="pl-1 text-xs">{currencySign}</span>
              </div>
              <div className="text-sm text-zinc-500 font-light">
                {productVariant?.weightValue}
                {weightUnitLocalized}
              </div>
            </div>
          </div>
        </div>
      </Link>

      <Counter count={quantity} lineId={id} />
    </div>
  );
};

type CartEmptyProps = {
  locale: Locale;
};

const CartEmpty = ({ locale }: CartEmptyProps) => {
  const { EMPTY_CART_DESCRIPTION } = getDictionary(locale);

  return (
    <div className="mt-8">
      <Image
        src="/static/eggs.png"
        alt=""
        width={96}
        height={96}
        className="mx-auto mb-2 grayscale opacity-60"
      />
      <div className="text-lg text-center font-normal text-zinc-500">
        {EMPTY_CART_DESCRIPTION}
      </div>
    </div>
  );
};

type DeliveryInfoBlockProps = {
  shippingPrice: number;
  method: Checkout['deliveryMethod'];
  currencySign: string;
  locale: Locale;
};

const DeliveryInfoBlock = ({
  shippingPrice,
  method,
  currencySign,
  locale,
}: DeliveryInfoBlockProps) => {
  const { DISCOUNT_LABEL, MIN_LABEL, DELIVERY_LABEL } = getDictionary(locale);

  let avg;
  let block;

  if (method === 'WAREHOUSE') {
    avg = '15–20';
    block = (
      <>
        {DISCOUNT_LABEL} 10<span className="text-xs">%</span>
      </>
    );
  }

  if (method === 'DELIVERY') {
    avg = '45–60';
    block = (
      <>
        {DELIVERY_LABEL} {shippingPrice}
        <span className="pl-1 text-xs">{currencySign}</span>
      </>
    );
  }

  return (
    <div className="flex flex-row gap-1 leading-tight">
      <div className="text-sm">
        {avg} {MIN_LABEL}
      </div>
      <span className="text-zinc-300">/</span>
      <div className="text-sm">{block}</div>
    </div>
  );
};
