// apps/food/app/components/Breadcrumbs.vue
<template>
  <div class="mb-6 flex flex-row justify-between items-center">
    <nav class="hidden lg:block">
      <ol class="flex flex-row flex-wrap gap-y-2 items-center">
        <li v-for="link in links" :key="link.title" class="relative max-w-[20rem] after:content-['/'] after:px-1 after:text-lg after:text-neutral-300 last:after:content-['']">
          <NuxtLink
            :to="link.href"
            class="px-3 py-2 inline-block leading-tight rounded-xl active:scale-95 lg:hover:bg-neutral-200 lg:hover:scale-95 lg:active:scale-90 duration-200 bg-neutral-50 dark:bg-neutral-700 data-[active=true]:bg-neutral-50"
            :data-active="link.href === '#'"
          >
            {{ link.title }}
          </NuxtLink>
        </li>
      </ol>
    </nav>

    <div class="w-full lg:w-auto mx-auto md:mx-0">
      <Button variant="secondary" @click="back()">
        <div class="flex flex-row gap-2 justify-center items-center">
          <Icon :name="icons.undo" size="20" /> {{ $t('common.return') }}
        </div>
      </Button>
    </div>
  </div>
</template>

<script setup lang="ts">
const { links } = defineProps<{
  links: { title: string, href: string }[]
}>()

const { icons } = useAppConfig()
const { back } = useRouter()
</script>

// apps/command-center/src/components/Breadcrumbs.tsx
import Link from 'next/link';
import { BackBlock } from './BackBlock';
import { getDictionary, prepareLocalizedLinks } from '../dictionaries';
import { PageKey } from '../lib/pages';
import { getLocale } from '../client/locale';
import { Button } from '@next-orders/ui';

type BreadcrumbsProps = {
  keys: PageKey[];
};

export const Breadcrumbs = ({ keys }: BreadcrumbsProps) => {
  const locale = getLocale();
  const dictionary = getDictionary(locale);

  // Dashboard page is always at start
  const preparedLinks = prepareLocalizedLinks(
    ['DASHBOARD', ...keys],
    dictionary,
  );

  const breadcrumbItems = preparedLinks.map((link, index) => (
    <BreadcrumbItem key={index} link={link} />
  ));

  return (
    <div className="mb-6 flex flex-row justify-between items-center">
      <nav className="hidden md:block">
        <ol role="list" className="flex flex-row">
          {breadcrumbItems}
        </ol>
      </nav>

      <BackBlock locale={locale} />
    </div>
  );
};

export type BreadcrumbLink = {
  title: string;
  href: string;
};

type BreadcrumbItemProps = {
  link: BreadcrumbLink;
};

const BreadcrumbItem = ({ link }: BreadcrumbItemProps) => {
  const isActive = link.href === '#';

  return (
    <li className="relative after:content-['/'] after:px-1 after:text-lg after:text-zinc-300 last:after:content-['']">
      <Link href={link.href} className="inline-block">
        <Button
          variant="secondary"
          data-active={isActive}
          className="data-[active=true]:bg-zinc-50"
        >
          {link.title}
        </Button>
      </Link>
    </li>
  );
};
