// apps/food/app/components/Input.vue
<template>
  <div>
    <label :for="id" class="mb-1 block text-sm font-medium text-neutral-900">{{ label }}</label>
    <input
      :id="id"
      type="text"
      value=""
      :placeholder="placeholder"
      class="px-4 py-3 mb-2 w-full border border-neutral-200 rounded-2xl outline-2 outline-offset-1 outline-neutral-500 placeholder:text-neutral-400"
    >
  </div>
</template>

<script setup lang="ts">
defineProps<{
  label: string
  placeholder?: string
}>()

const id = useId()
</script>

// apps/command-center/src/components/Input.tsx
type InputProps = {
  type?: 'text' | 'password' | 'number';
  name: string;
  label: string;
  placeholder?: string;
  isRequired: boolean;
  value: string;
  // eslint-disable-next-line no-unused-vars
  onChange: (value: string) => void;
};

export const Input = ({
  name,
  label,
  placeholder,
  isRequired,
  value,
  onChange,
  type = 'text',
}: InputProps) => {
  return (
    <>
      <label
        htmlFor={name}
        className="mb-1 block text-sm font-medium text-zinc-900"
      >
        {label} {isRequired && '*'}
      </label>
      <input
        type={type}
        id={name}
        name={name}
        placeholder={placeholder}
        required={isRequired}
        value={value}
        onWheel={(event) => event.currentTarget.blur()}
        onChange={(event) => onChange(event.currentTarget.value)}
        className="peer block w-full rounded-2xl border border-zinc-200 py-3 px-4 text-base outline-2 outline-offset-1 outline-zinc-500 placeholder:text-zinc-400"
      />
    </>
  );
};
