// apps/food/app/components/Navigation.vue
<template>
  <nav
    class="z-10 w-0 hidden md:block md:w-72 fixed top-16 data-[active=true]:w-full data-[active=true]:block md:data-[active=true]:w-72"
    :data-active="isNavbarOpened"
  >
    <div class="w-full bg-gray-50 px-4 pt-4 border-r border-gray-100">
      <div class="h-screen overflow-y-auto">
        <div class="mb-8">
          <NuxtLink
            href="/"
            class="font-medium text-xl text-primary"
          >
            {{ channelData?.channel?.name }}
          </NuxtLink>
          <div class="mt-1 text-sm leading-tight">
            {{ channelData?.channel?.description }}
          </div>
        </div>

        <div v-if="checkout" class="mb-8">
          <DeliveryInfoBlock />

          <button
            class="flex flex-row gap-2 items-center active:scale-95 lg:hover:scale-95 lg:active:scale-90 duration-200"
            @click="isDeliveryInfoModalOpened = !isDeliveryInfoModalOpened"
          >
            <Icon :name="icons.link" /> показать детали
          </button>
        </div>

        <div class="mb-32">
          <p class="font-medium text-lg">
            Каталог
          </p>

          <LinkButton
            v-for="category in channelData?.categories"
            :key="category.id"
            :link="`/catalog/${category.slug}`"
            :label="category.name"
          />
        </div>
      </div>
    </div>
  </nav>
</template>

<script setup lang="ts">
const { isNavbarOpened, isDeliveryInfoModalOpened } = useApp()
const { icons } = useAppConfig()
const channelData = await useChannel()
const { checkout } = await useCheckout()
</script>

// apps/command-center/src/components/Navigation.tsx
'use client';

import React from 'react';
import { MenuItem } from '../types';
import { TablerIcon } from './TablerIcon';
import { useUIStore } from '../store/ui';
import { LinkButton } from './LinkButton';
import { getDictionary, Locale } from '../dictionaries';

type NavigationProps = {
  menu: MenuItem[];
  locale: Locale;
};

export const Navigation = ({ menu, locale }: NavigationProps) => {
  const isNavbarOpened = useUIStore((state) => state.isNavbarOpened);

  const { COMMAND_CENTER_LABEL } = getDictionary(locale);

  const menuBlock = menu?.map((item) => (
    <LinkButton
      key={item.id}
      link={item.href}
      label={item.label}
      icon={<TablerIcon icon={item.icon} />}
    />
  ));

  return (
    <nav
      data-active={isNavbarOpened}
      className="z-10 w-0 invisible 2xl:visible 2xl:w-72 fixed top-16 data-[active=true]:w-full data-[active=true]:visible md:data-[active=true]:w-72"
    >
      <div className="w-full bg-zinc-50 px-4 pt-4 border-r border-zinc-100">
        <div className="h-screen overflow-y-auto">
          <div className="mb-32">
            <div className="flex flex-row items-center py-2">
              <div className="font-semibold text-xl">
                {COMMAND_CENTER_LABEL}
              </div>
            </div>

            {menuBlock}
          </div>
        </div>
      </div>
    </nav>
  );
};
