// src/components/Navigation.tsx
"use client";

import Link from "next/link";
import { IconClock, IconLink, IconTruckDelivery } from "@tabler/icons-react";
import type { Channel, Shop } from "@next-orders/api-sdk";
import { LinkButton } from "@/components/LinkButton";
import { useUIStore } from "@/store/ui";

type NavigationProps = {
  shop: Shop | null;
  channel: Channel | null;
};

export const Navigation = ({ shop, channel }: NavigationProps) => {
  const isNavbarOpened = useUIStore((state) => state.isNavbarOpened);
  const toggleDeliveryInfoModal = useUIStore(
    (state) => state.toggleDeliveryInfoModal,
  );

  const menu = channel?.menus[0];

  const buttons = menu?.categories?.map((item) => {
    return (
      <LinkButton
        key={item.id}
        link={"/catalog/" + item.slug}
        label={item.name}
        iconUrl={item.iconUrl}
      />
    );
  });

  return (
    <nav
      className="z-10 w-0 hidden md:block md:w-72 fixed top-16 data-[active=true]:w-full data-[active=true]:block md:data-[active=true]:w-72"
      data-active={isNavbarOpened}
    >
      <div className="w-full bg-zinc-50 px-4 pt-4 border-r border-zinc-100">
        <div className="h-screen overflow-y-auto">
          <div className="mb-8">
            <Link
              href="/"
              className="font-medium text-xl"
              style={{ color: channel?.accentTextColor }}
            >
              {shop?.name}
            </Link>
            <div className="mt-1 text-sm leading-tight">
              {shop?.description}
            </div>
          </div>

          <div className="mb-8">
            <p className="font-medium text-lg mb-2">Delivery</p>

            <div className="flex flex-row gap-2 items-center mb-2">
              <IconClock stroke={1.5} /> today until 22:00
            </div>

            <div className="flex flex-row gap-2 items-center mb-2">
              <IconTruckDelivery stroke={1.5} />
              <div>
                free from 25
                <span className="text-sm">$</span>
              </div>
            </div>

            <button
              onClick={toggleDeliveryInfoModal}
              className="flex flex-row gap-2 items-center hover:scale-95 duration-200"
            >
              <IconLink stroke={1.5} /> show details
            </button>
          </div>

          <div className="mb-32">
            <p className="font-medium text-lg">Catalog</p>
            {buttons}
          </div>
        </div>
      </div>
    </nav>
  );
};

// apps/food/app/components/Navigation/index.vue
<template>
  <nav
    class="z-10 w-0 hidden md:block md:w-72 fixed top-16 data-[active=true]:w-full data-[active=true]:block md:data-[active=true]:w-72"
    :data-active="isNavbarOpened"
  >
    <div class="w-full bg-neutral-50 dark:bg-neutral-700 px-4 pt-4 border-r border-neutral-100 dark:border-neutral-500">
      <div class="h-screen overflow-y-auto">
        <div class="mb-8">
          <NuxtLink
            href="/"
            class="font-medium text-xl text-primary"
          >
            {{ channel?.name }}
          </NuxtLink>
          <div class="mt-1 text-sm leading-tight">
            {{ channel?.description }}
          </div>
        </div>

        <div v-if="checkout" class="mb-8">
          <DeliveryInfoBlock />

          <button
            class="flex flex-row gap-2 items-center active:scale-95 lg:hover:scale-95 lg:active:scale-90 duration-200"
            @click="isDeliveryInfoModalOpened = !isDeliveryInfoModalOpened"
          >
            <Icon :name="icons.link" /> {{ $t('app.show-details-label') }}
          </button>
        </div>

        <div class="mb-32">
          <p class="font-medium text-lg">
            {{ $t('app.catalog') }}
          </p>

          <NavigationButton
            v-for="category in categories"
            :key="category.id"
            :link="`/catalog/${category.slug}`"
            :label="category.name"
          />
        </div>
      </div>
    </div>
  </nav>
</template>

<script setup lang="ts">
const { isNavbarOpened, isDeliveryInfoModalOpened } = useApp()
const { icons } = useAppConfig()
const { channel, categories } = await useChannel()
const { checkout } = await useCheckout()
</script>
